# Generated by Django 4.2.9 on 2024-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('avatarurl', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
