# Generated by Django 4.2.9 on 2024-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='avatarurl',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='last',
        ),
    ]
