# Generated by Django 4.2.9 on 2024-02-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_avatarurl_contact_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favourite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
