# Generated by Django 4.2.9 on 2024-02-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
