# Generated by Django 4.2.9 on 2024-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_favourite_contact_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='favorite',
            field=models.CharField(max_length=10),
        ),
    ]
