# Generated by Django 4.2.9 on 2024-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='favorite',
            field=models.BooleanField(),
        ),
    ]
